interfaces:
  GigabitEthernet 1/1:
    description: "u38-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/2:
    description: "u37-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/3:
    description: "u36-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/4:
    description: "u35-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/5:
    description: "u34-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/6:
    description: "u33-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/7:
    description: "u32-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/8:
    description: "u31-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/9:
    description: "u30-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/10:
    description: "u29-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/11:
    description: "u28-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/12:
    description: "u27-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/13:
    description: "u26-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/14:
    description: "u25-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/15:
    description: "u24-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/16:
    description: "u23-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/17:
    description: "u22-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/18:
    description: "u21-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/19:
    description: "u20-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/20:
    description: "u19-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/21:
    description: "u18-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/22:
    description: "u17-ipmi"
    state: "up"
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/23:
    state: "down"
  GigabitEthernet 1/24:
    state: "down"
  GigabitEthernet 1/25:
    state: "down"
  GigabitEthernet 1/26:
    state: "down"
  GigabitEthernet 1/27:
    state: "down"
  GigabitEthernet 1/28:
    state: "down"
  GigabitEthernet 1/29:
    state: "down"
  GigabitEthernet 1/30:
    state: "down"
  GigabitEthernet 1/31:
    state: "down"
  GigabitEthernet 1/32:
    state: "down"
  GigabitEthernet 1/33:
    state: "down"
  GigabitEthernet 1/34:
    state: "down"
  GigabitEthernet 1/35:
    state: "down"
  GigabitEthernet 1/36:
    state: "down"
  GigabitEthernet 1/37:
    state: "down"
  GigabitEthernet 1/38:
    state: "down"
  GigabitEthernet 1/39:
    state: "down"
  GigabitEthernet 1/40:
    state: "down"
  GigabitEthernet 1/41:
    state: "down"
  GigabitEthernet 1/42:
    state: "down"
  GigabitEthernet 1/43:
    state: "down"
  GigabitEthernet 1/44:
    state: "down"
  GigabitEthernet 1/45:
    state: "down"
  GigabitEthernet 1/46:
    state: "down"
  GigabitEthernet 1/47:
    state: "down"
  GigabitEthernet 1/48:
    description: "OCT-MCORE-2"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged: "all"
  TenGigabitEthernet 1/49:
    state: "down"
  TenGigabitEthernet 1/50:
    state: "down"
  TenGigabitEthernet 1/51:
    description: "OCT2-SW-MGMT Port 45"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/52:
    description: "OCT2-SW-MGMT Port 46"
    state: "up"
    mtu: 9216
  Port-channel 101:
    description: "OCT4-SW-TORS Uplink"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged: "all"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/51"
      - "TenGigabitEthernet 1/52"
  Vlan 931:
    state: "up"
    ip4: "10.81.2.42/20"
