port_channels:
  1:
    description: "OCT-CORE-3 LAG"
    state: "up"
    tagged:
      # CSAIL
      - 10
      # MOC Public IPs
      - 127
      # MOC
      - 207
      - 208
      - 213
      - 250
      # ESI
      - 351:499
      - 520:622
      - 623
      - 624:630
      # MGMT
      - 911
      - 913
      # CloudLab Testing
      - 920
      - 921
      # CSAIL
      - 3801
      - 3803
    portmode: "trunk"
    mtu: 9216
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/53"
      - "1/54"
