---
- name: Load schema
  ansible.builtin.set_fact:
    schema: >-
      {{
        lookup('ansible.builtin.file', schema_path) | from_yaml
      }}

- name: Validate data
  ansible.builtin.set_fact:
    validation_errors: >-
      {{
      lookup('ansible.utils.validate', data, schema,
      engine='ansible.utils.jsonschema',
      draft=jsonschema_draft)
      }}

- name: Print validation
  when: validation_errors
  block:
    - name: Display validation errors
      ansible.builtin.debug:
        var: validation_errors

    - name: Fail due to validation errors
      ansible.builtin.fail.fail:
        msg: Failing due to validation errors.
