port_channels:
  10:
    description: "OCT-CORE-1 LAG"
    state: "up"
    tagged: "all"
    mtu: 9216
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/54"
    custom:
      - "vlt-peer-lag port-channel 10"
  100:
    description: "OCT5-SW-TORS-B VLT LAG"
    state: "up"
    mtu: 9216
    mode: "normal"
    interfaces:
      - "1/51"
      - "1/52"
