---
- name: Include validation playbook
  ansible.builtin.import_playbook: validate.yaml

- name: Main site playbook
  hosts: all
  connection: network_cli
  tasks:
    - name: Include common role
      ansible.builtin.include_role:
        name: common
