---
- name: Include validation playbook
  ansible.builtin.import_playbook: validate.yaml

- hosts: all
  connection: network_cli
  tasks:
    - include_role:
        name: common
    - include_role:
        name: snmp
