---
- name: Validate configuration
  hosts: all
  gather_facts: false
  tags: [validate]

  # Abort the playbook if any host fails validation
  any_errors_fatal: true

  tasks:
    - name: Validate VLAN Configuration
      ansible.builtin.include_role:
        name: validate
      vars:
        schema_path: vlan_configuration.yaml
        data: "{{ vlans }}"

    - name: Validate Interface Configuration
      when: interfaces is defined
      ansible.builtin.include_role:
        name: validate
        apply:
          delegate_to: localhost
      vars:
        schema_path: interface_configuration.yaml
        data: "{{ interfaces }}"

    - name: Validate VLAN Interface Configuration
      when: vlan_interfaces is defined
      ansible.builtin.include_role:
        name: validate
        apply:
          delegate_to: localhost
      vars:
        schema_path: vlan_interface_configuration.yaml
        data: "{{ vlan_interfaces }}"

    - name: Validate Port Channel Configuration
      when: port_channels is defined
      ansible.builtin.include_role:
        name: validate
        apply:
          delegate_to: localhost
      vars:
        schema_path: port_channel_configuration.yaml
        data: "{{ port_channels }}"
