interfaces:
  GigabitEthernet 1/1:
    state: "down"
  GigabitEthernet 1/2:
    state: "down"
  GigabitEthernet 1/3:
    description: "MOC-R4PAC##-SW-MGMT"
    state: "up"
    portmode: "trunk"
    tagged: "all"
  GigabitEthernet 1/4:
    description: "MOC-R4PAC##-SW-MGMT"
    state: "up"
    portmode: "trunk"
    tagged: "all"
  GigabitEthernet 1/5:
    description: "MOC-R4PAC10-SW-MGMT"
    state: "up"
    portmode: "trunk"
    tagged: "all"
  GigabitEthernet 1/6:
    description: "MOC-R4PAC08-SW-MGMT"
    state: "up"
    portmode: "trunk"
    tagged: "all"
  GigabitEthernet 1/7:
    description: "MOC-R4PAC04-SW-MGMT"
    state: "up"
    portmode: "trunk"
    tagged: "all"
  GigabitEthernet 1/8:
    description: "MOC-R4PAC02-SW-MGMT"
    state: "up"
    portmode: "trunk"
    tagged: "all"
  GigabitEthernet 1/9:
    state: "down"
  GigabitEthernet 1/10:
    state: "down"
  GigabitEthernet 1/11:
    state: "down"
  GigabitEthernet 1/12:
    state: "down"
  GigabitEthernet 1/13:
    state: "down"
  GigabitEthernet 1/14:
    state: "down"
  GigabitEthernet 1/15:
    state: "down"
  GigabitEthernet 1/16:
    state: "down"
  GigabitEthernet 1/17:
    state: "down"
  GigabitEthernet 1/18:
    state: "down"
  GigabitEthernet 1/19:
    state: "down"
  GigabitEthernet 1/20:
    state: "down"
  GigabitEthernet 1/21:
    state: "down"
  GigabitEthernet 1/22:
    state: "down"
  GigabitEthernet 1/23:
    state: "down"
  GigabitEthernet 1/24:
    state: "down"
  GigabitEthernet 1/25:
    state: "down"
  GigabitEthernet 1/26:
    state: "down"
  GigabitEthernet 1/27:
    state: "down"
  GigabitEthernet 1/28:
    state: "down"
  GigabitEthernet 1/29:
    state: "down"
  GigabitEthernet 1/30:
    state: "down"
  GigabitEthernet 1/31:
    state: "down"
  GigabitEthernet 1/32:
    state: "down"
  GigabitEthernet 1/33:
    state: "down"
  GigabitEthernet 1/34:
    state: "down"
  GigabitEthernet 1/35:
    state: "down"
  GigabitEthernet 1/36:
    state: "down"
  GigabitEthernet 1/37:
    state: "down"
  GigabitEthernet 1/38:
    state: "down"
  GigabitEthernet 1/39:
    state: "down"
  GigabitEthernet 1/40:
    state: "down"
  GigabitEthernet 1/41:
    state: "down"
  GigabitEthernet 1/42:
    state: "down"
  GigabitEthernet 1/43:
    state: "down"
  GigabitEthernet 1/44:
    state: "down"
  GigabitEthernet 1/45:
    state: "down"
  GigabitEthernet 1/46:
    state: "down"
  GigabitEthernet 1/47:
    state: "down"
  GigabitEthernet 1/48:
    state: "down"
  TenGigabitEthernet 1/49:
    description: "MOC-CORE-3 Port 33"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/50:
    description: "MOC-CORE-4 Port 33"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/51:
    description: "MOC-MCORE-1 Port 51"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/52:
    description: "MOC-MCORE-1 Port 52"
    state: "up"
    mtu: 9216
  Port-channel 10:
    description: "MOC-MCORE-1 LAG"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged: "all"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/51"
      - "TenGigabitEthernet 1/52"
  Port-channel 101:
    description: "MOC-CORE Uplink"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged: "all"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/49"
      - "TenGigabitEthernet 1/50"
  Vlan 930:
    state: "up"
    ip4: "10.80.1.12/20"
