---
# Define OS9 connection parameters
- name: Define OS9 Connection Parameters
  ansible.builtin.set_fact:
    ansible_become: true
    ansible_become_method: enable
    ansible_ssh_user: "{{ sw_secret['user'] }}"
    ansible_ssh_pass: "{{ sw_secret['pass'] }}"
    ansible_become_pass: "{{ sw_secret['pass'] }}"

- name: Gather serial number
  dellemc.os9.os9_command:
    commands:
      - show inventory | grep "\* 1"
  register: serial_number

- name: Print serial number
  ansible.builtin.debug:
    msg: "{{ serial_number.stdout }}"
