---
$id: https://massopen.cloud/schemas/interface_configuration.yaml
title: Interface Configuration
type: object
patternProperties:
  "^[0-9]+(/[0-9]+)+$":
    $ref: "#/$defs/interface"
additionalProperties: false
$defs:
  interface:
    type: object
    additionalProperties: false
    properties:
      description:
        type: string
      admin:
        type: string
        enum:
          - up
          - down
      untagged:
        type: integer
        minimum: 1
        maximum: 4095
      tagged:
        anyOf:
          - type: array
            items:
              type: integer
              minimum: 2
              maximum: 4095
          - type: string
            enum:
              - all
      managed:
        type: string
        enum:
          - "yes"
          - "no"
          - vlans
      stp-edge:
        type: string
      mtu:
        type: integer
        minimum: 594
        maximum: 9416
      fanout:
        type: string
        enum:
          - single
          - dual
          - quad
      fanout_speed:
        type: string
        enum:
          - 10G
          - 25G
          - 40G
          - 100G
      ip4:
        type: string
      ip6:
        type: string
      keepalive:
        type: string
      custom:
        type: array
        items:
          type: string
  required:
    - admin
