$id: https://massopen.cloud/schemas/interface_configuration.yaml
title: Port Channel Configuration
type: object
patternProperties:
  "^[0-9]+$":
    $ref: "#/$defs/port_channel"
additionalProperties: false
$defs:
  port_channel:
    type: object
    additionalProperties: false
    properties:
      description:
        type: string
      admin:
        type: string
        enum:
          - up
          - down
      untagged:
        type: integer
        minimum: 0
        maximum: 4096
      tagged:
        type: array
        items:
          type: integer
          minimum: 0
          maximum: 4096
      stp-edge:
        type: string
      mtu:
        type: integer
        minimum: 0
      ip4:
        type: string
      ip6:
        type: string
      keepalive:
        type: string
      mode:
        type: string
      lacp-rate:
        type: string
      interfaces:
        type: array
        items:
          type: string
  required:
    - description
