---
$id: https://massopen.cloud/schemas/port_channel_configuration.yaml
title: Port Channel Configuration
anyOf:
  - type: object
    patternProperties:
      "^[0-9]+$":
        $ref: "#/$defs/port_channel"
    additionalProperties: false
  - type: "null"
$defs:
  port_channel:
    type: object
    additionalProperties: false
    properties:
      description:
        type: string
      state:
        type: string
        enum:
          - up
          - down
      untagged:
        type: integer
        minimum: 1
        maximum: 4095
      tagged:
        anyOf:
          - type: array
            items:
              type: integer
              minimum: 2
              maximum: 4095
          - type: string
            enum:
              - all
      portmode:
        type: string
        enum:
          - access
          - trunk
          - hybrid
      mtu:
        type: integer
        minimum: 594
        maximum: 9416
      ip4:
        type: string
      ip6:
        type: string
      mode:
        type: string
        enum:
          - normal
          - lacp
      lacp-rate:
        type: string
      interfaces:
        type: array
        items:
          type: string
      custom:
        type: array
        items:
          type: string
  required:
    - description
    - admin
    - mode
    - interfaces
