---
$id: https://massopen.cloud/schemas/vlan_interface_configuration.yaml
title: VLAN Interface Configuration
anyOf:
  - type: object
    patternProperties:
      "^[0-9]+$":
        $ref: "#/$defs/vlan_interface"
    additionalProperties: false
  - type: "null"
$defs:
  vlan_interface:
    type: object
    additionalProperties: false
    properties:
      state:
        type: string
        enum:
          - up
          - down
      mtu:
        type: integer
        minimum: 594
        maximum: 9416
      ip4:
        type: string
      ip6:
        type: string
      custom:
        type: array
        items:
          type: string
  required:
    - admin
