---
# Define OS9 connection parameters
- name: Define OS9 Connection Parameters
  ansible.builtin.set_fact:
    ansible_become: true
    ansible_become_method: enable
    ansible_ssh_user: "{{ sw_secret['user'] }}"
    ansible_ssh_pass: "{{ sw_secret['pass'] }}"
    ansible_become_pass: "{{ sw_secret['pass'] }}"

- name: Save Config
  dellemc.os9.os9_config:
    save: true
