---
vlans:
  100:
    name: "VLAN 100"
    description: "This is the description of example vlan 100"
    switches:
      - oct_tors
  101:
    name: "VLAN 101"
    description: "This is the description of example vlan 101"
    switches:
      - oct_tors
  102:
    name: "VLAN 102"
    description: "hello world"
    switches:
      - oct_tors
