interfaces:
  hundredGigE 1/1:
    description: "U03-FPGA-1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/2:
    description: "U03-FPGA-2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/3:
    description: "U05-FPGA-1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/4:
    description: "U05-FPGA-2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/5:
    description: "U07-FPGA-1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/6:
    description: "U07-FPGA-2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/7:
    description: "U09-FPGA-1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/8:
    description: "U09-FPGA-2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/9:
    description: "U11-FPGA-1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/10:
    description: "U11-FPGA-2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/11:
    description: "U13-FPGA-1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/12:
    description: "U13-FPGA-2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/13:
    description: "U15-FPGA-1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/14:
    description: "U15-FPGA-2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/15:
    description: "U17-FPGA-1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/16:
    description: "U17-FPGA-2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/17:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/17/1:
    description: "U03-Experiment"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/17/2:
    description: "U05-Experiment"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/17/3:
    description: "U07-Experiment"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/17/4:
    description: "U09-Experiment"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/18:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/18/1:
    description: "U11-Experiment"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/18/2:
    description: "U13-Experiment"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/18/3:
    description: "U15-Experiment"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/18/4:
    description: "U17-Experiment"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/19:
    state: "down"
  hundredGigE 1/20:
    state: "down"
  hundredGigE 1/21:
    state: "down"
  hundredGigE 1/22:
    state: "down"
  hundredGigE 1/23:
    state: "down"
  hundredGigE 1/24:
    state: "down"
  hundredGigE 1/25:
    state: "down"
  hundredGigE 1/26:
    state: "down"
  hundredGigE 1/27:
    state: "down"
  hundredGigE 1/28:
    state: "down"
  hundredGigE 1/29:
    description: "OCT10-SW-TORS-A Port 25"
    state: "up"
    mtu: 9216
  hundredGigE 1/30:
    description: "OCT10-SW-TORS-A Port 26"
    state: "up"
    mtu: 9216
  hundredGigE 1/31:
    description: "OCT10-SW-TORS-A Port 27"
    state: "up"
    mtu: 9216
  hundredGigE 1/32:
    description: "OCT10-SW-TORS-A Port 28"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/33:
    state: "down"
  TenGigabitEthernet 1/34:
    state: "down"
  Port-channel 1:
    description: "OCT10-SW-TORS-A LAG"
    state: "up"
    portmode: "trunk"
    tagged: "all"
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/29"
      - "hundredGigE 1/30"
      - "hundredGigE 1/31"
      - "hundredGigE 1/32"
  Vlan 910:
    state: "up"
    ip4: "10.0.0.19/22"
  Vlan 931:
    state: "up"
    ip4: "10.81.2.102/20"
