interfaces:
  hundredGigE 1/1:
    description: "OCT-CORE-1 Port 29 Po10"
    state: "up"
    mtu: 9216
  hundredGigE 1/2:
    description: "OCT-CORE-2 Port 29 Po10"
    state: "up"
    mtu: 9216
  hundredGigE 1/3:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/3/1:
    description: "CL-SW-TORS Port #### Po1"
    state: "up"
    mtu: 9216
  hundredGigE 1/4:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/4/1:
    description: "CL-SW-TORS Port #### Po1"
    state: "up"
    mtu: 9216
  hundredGigE 1/5:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/5/1:
    description: "OCT1-SW-TORS Port #### Po2"
    state: "up"
    mtu: 9216
  hundredGigE 1/6:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/6/1:
    description: "OCT1-SW-TORS Port #### Po2"
    state: "up"
    mtu: 9216
  hundredGigE 1/7:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/7/1:
    description: "OCT2-SW-TORS Port #### Po3"
    state: "up"
    mtu: 9216
  hundredGigE 1/8:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/8/1:
    description: "OCT2-SW-TORS Port #### Po3"
    state: "up"
    mtu: 9216
  hundredGigE 1/9:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/9/1:
    description: "OCT3-SW-TORS Port #### Po4"
    state: "up"
    mtu: 9216
  hundredGigE 1/10:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/10/1:
    description: "OCT3-SW-TORS Port #### Po4"
    state: "up"
    mtu: 9216
  hundredGigE 1/11:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/11/1:
    description: "OCT4-SW-TORS Port #### Po5"
    state: "up"
    mtu: 9216
  hundredGigE 1/12:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/12/1:
    description: "OCT4-SW-TORS Port #### Po5"
    state: "up"
    mtu: 9216
  hundredGigE 1/13:
    description: "OCT9-SW-TORS-B Port #### Po7"
    state: "up"
    mtu: 9216
  hundredGigE 1/14:
    description: "OCT9-SW-TORS-A Port #### Po6"
    state: "up"
    mtu: 9216
  hundredGigE 1/15:
    state: "down"
  hundredGigE 1/16:
    state: "down"
  hundredGigE 1/17:
    state: "down"
  hundredGigE 1/18:
    state: "down"
  hundredGigE 1/19:
    state: "down"
  hundredGigE 1/20:
    state: "down"
  hundredGigE 1/21:
    state: "down"
  hundredGigE 1/22:
    state: "down"
  hundredGigE 1/23:
    state: "down"
  hundredGigE 1/24:
    state: "down"
  hundredGigE 1/25:
    state: "down"
  hundredGigE 1/26:
    state: "down"
  hundredGigE 1/27:
    description: "OCT-CORE-4 Port 27 VLT"
    state: "up"
  hundredGigE 1/28:
    description: "OCT-CORE-4 Port 28 VLT"
    state: "up"
  hundredGigE 1/29:
    description: "FABRIC-CISCO"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    tagged:
      - 3100
      - 3101
      - 3102
      - 3103
      - 3104
      - 3105
      - 3106
      - 3107
      - 3108
      - 3109
    autoneg: false
  hundredGigE 1/30:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/30/1:
    description: "UMA PA-3220 Port ####"
    state: "up"
    portmode: "tagged"
    tagged:
      - 57
      - 84
      - 920
  TenGigabitEthernet 1/30/2:
    description: "Inaccessible"
    state: "down"
  TenGigabitEthernet 1/30/3:
    description: "Inaccessible"
    state: "down"
  TenGigabitEthernet 1/30/4:
    description: "Inaccessible"
    state: "down"
  hundredGigE 1/31:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/31/1:
    description: "UNITY-CORE-1 Port #### Po200"
    state: "up"
    mtu: 9216
  hundredGigE 1/32:
    state: "down"
  TenGigabitEthernet 1/33:
    description: "OCT-MCORE-2 Port 51 Po300"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/34:
    description: "OCT-CORE-4 Port 34 VLT Heartbeat"
    state: "up"
    ip4: "10.255.255.1/30"
  Port-channel 1:
    description: "CL-SW-TORS LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      # UMA Public IPs
      - 84
      # MGMT
      - 910
      - 930
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "fortyGigE 1/3/1"
      - "fortyGigE 1/4/1"
  Port-channel 2:
    description: "OCT1-SW-TORS LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      # UMA Public IPs
      - 84
      # MGMT
      - 910
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "fortyGigE 1/5/1"
      - "fortyGigE 1/6/1"
  Port-channel 3:
    description: "OCT2-SW-TORS LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      # UMA Public IPs
      - 84
      # MGMT
      - 910
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "fortyGigE 1/7/1"
      - "fortyGigE 1/8/1"
  Port-channel 5:
    description: "OCT4-SW-TORS LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      # CSAIL
      - 10
      # MOC Public IPs
      - 127
      # MOC
      - 204
      - 207
      - 208
      - 213
      - 250
      # ESI
      - 351:499
      - 520:622
      - 623
      - 624:630
      # MGMT
      - 911
      - 913
      # CloudLab Testing
      - 920
      - 921
      # CSAIL
      - 3801
      - 3802
      - 3803
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "fortyGigE 1/11/1"
      - "fortyGigE 1/12/1"
  Port-channel 6:
    description: "OCT9-SW-TORS-A LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      # UMA Public IPs
      - 84
      # MGMT
      - 910
      - 930
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/13"
  Port-channel 7:
    description: "OCT9-SW-TORS-B LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      # UMA Public IPs
      - 84
      # MGMT
      - 910
      - 930
    mtu: 9216
    lacp-rate: "fast"
    interfaces:
      - "hundredGigE 1/14"
  Port-channel 10:
    description: "OCT-CORE-1 and OCT-CORE-2 Core LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      # CSAIL
      - 10
      # UMA Public IPs
      - 84
      # MOC Public IPs
      - 105
      - 127
      # MOC
      - 204
      - 207
      - 208
      - 213
      - 250
      # Unity
      - 300
      # ESI
      - 351:499
      - 520:622
      - 623
      - 624:630
      # MGMT
      - 911
      - 913
      - 930
      # AL2S VLANs
      - 3100
      - 3101
      - 3102
      - 3103
      - 3104
      - 3105
      - 3106
      - 3107
      - 3108
      - 3109
      # CSAIL
      - 3801
      - 3802
      - 3803
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/1"
      - "hundredGigE 1/2"
    mlag: "Port-channel 10"
  Port-channel 100:
    description: "OCT-CORE-4 VLT LAG"
    state: "up"
    mtu: 9216
    lag-members:
      - "hundredGigE 1/27"
      - "hundredGigE 1/28"
  Port-channel 200:
    description: "UNITY-CORE-1 LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      # UNITY
      - 300
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "fortyGigE 1/31/1"
    mlag: "Port-channel 200"
  Port-channel 300:
    description: "OCT-MCORE-2 uplink"
    state: "up"
    portmode: "trunk"
    tagged:
      # MGMT
      - 910
      - 911
      - 912
      - 913
      - 930
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/33"
    mlag: "Port-channel 300"
  Vlan 910:
    state: "up"
    ip4: "10.0.0.14/22"
