port_channels:
  1:
    description: "CL-SW-TORS LAG"
    state: "up"
    tagged: "all"
    mtu: 9216
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/3/1"
      - "1/4/1"
  2:
    description: "OCT1-SW-TORS LAG"
    state: "up"
    tagged: "all"
    mtu: 9216
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/5/1"
      - "1/6/1"
  3:
    description: "OCT2-SW-TORS LAG"
    state: "up"
    tagged: "all"
    mtu: 9216
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/7/1"
      - "1/8/1"
  4:
    description: "OCT3-SW-TORS LAG"
    state: "up"
    tagged: "all"
    mtu: 9216
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/9/1"
      - "1/10/1"
  5:
    description: "OCT4-SW-TORS LAG"
    state: "up"
    tagged: "all"
    mtu: 9216
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/11/1"
      - "1/12/1"
  6:
    description: "OCT9-SW-TORS-A LAG"
    state: "up"
    tagged: "all"
    mtu: 9216
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/13"
  7:
    description: "OCT9-SW-TORS-B LAG"
    state: "up"
    tagged: "all"
    mtu: 9216
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/14"
  10:
    description: "OCT-CORE-1 and OCT-CORE-2 Core LAG"
    state: "up"
    tagged: "all"
    mtu: 9216
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/1"
      - "1/2"
    custom:
      - "vlt-peer-lag port-channel 10"
  100:
    description: "OCT-CORE-4 VLT LAG"
    state: "up"
    mode: "normal"
    interfaces:
      - "1/27"
      - "1/28"
  200:
    description: "UNITY-CORE-1 LAG"
    state: "up"
    tagged:
      - 300
      - 301
    mtu: 9216
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/31/1"
    custom:
      - "vlt-peer-lag port-channel 200"
  300:
    description: "OCT-MCORE-2 uplink"
    state: "up"
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/33"
    tagged:
      - 910
      - 911
      - 912
      - 930
    custom:
      - "vlt-peer-lag port-channel 300"
