interfaces:
  hundredGigE 1/1:
    description: "MOC-R4PAC##-SW-TORS-B Port 30"
    state: "up"
    mtu: 9216
  hundredGigE 1/2:
    description: "MOC-R4PAC##-SW-TORS-B Port 30"
    state: "up"
    mtu: 9216
  hundredGigE 1/3:
    description: "MOC-R4PAC##-SW-TORS-B Port 30"
    state: "up"
    mtu: 9216
  hundredGigE 1/4:
    description: "MOC-R4PAC##-SW-TORS-B Port 30"
    state: "up"
    mtu: 9216
  hundredGigE 1/5:
    description: "MOC-R4PAC##-SW-TORS-B Port 30"
    state: "up"
    mtu: 9216
  hundredGigE 1/6:
    description: "MOC-R4PAC04-SW-TORS Port 54"
    state: "up"
    mtu: 9216
  hundredGigE 1/7:
    description: "MOC-R4PAC04-SW-TORS Port 54"
    state: "up"
    mtu: 9216
  hundredGigE 1/8:
    state: "down"
  hundredGigE 1/9:
    state: "down"
  hundredGigE 1/10:
    state: "down"
  hundredGigE 1/11:
    state: "down"
  hundredGigE 1/12:
    state: "down"
  hundredGigE 1/13:
    state: "down"
  hundredGigE 1/14:
    state: "down"
  hundredGigE 1/15:
    state: "down"
  hundredGigE 1/16:
    state: "down"
  hundredGigE 1/17:
    state: "down"
  hundredGigE 1/18:
    state: "down"
  hundredGigE 1/19:
    state: "down"
  hundredGigE 1/20:
    state: "down"
  hundredGigE 1/21:
    state: "down"
  hundredGigE 1/22:
    state: "down"
  hundredGigE 1/23:
    state: "down"
  hundredGigE 1/24:
    state: "down"
  hundredGigE 1/25:
    state: "down"
  hundredGigE 1/26:
    state: "down"
  hundredGigE 1/27:
    state: "down"
  hundredGigE 1/28:
    state: "down"
  hundredGigE 1/29:
    description: "MOC-CORE-2 Port 29"
    state: "up"
    mtu: 9216
  hundredGigE 1/30:
    description: "MOC-CORE-1 Port 30"
    state: "up"
    mtu: 9216
  hundredGigE 1/31:
    description: "MOC-CORE-3 Port 31 VLT"
    state: "up"
  hundredGigE 1/32:
    description: "MOC-CORE-3 Port 32 VLT"
    state: "up"
  TenGigabitEthernet 1/33:
    description: "MOC-MCORE-2 Port 50"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/34:
    state: "down"
  Port-channel 10:
    description: "MOC Core Link to CORE-1 and CORE-2"
    state: "up"
    portmode: "trunk"
    tagged: "all"
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/29"
      - "hundredGigE 1/30"
    mlag: "Port-channel 10"
  Port-channel 20:
    description: "MOC-R4PAC## Link"
    state: "up"
    portmode: "trunk"
    tagged: "all"
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/1"
    mlag: "Port-channel 20"
    stp:
      rootguard: true
  Port-channel 30:
    description: "MOC-R4PAC## Link"
    state: "up"
    portmode: "trunk"
    tagged: "all"
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/2"
    mlag: "Port-channel 30"
    stp:
      rootguard: true
  Port-channel 40:
    description: "MOC-R4PAC## Link"
    state: "up"
    portmode: "trunk"
    tagged: "all"
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/3"
    mlag: "Port-channel 40"
    stp:
      rootguard: true
  Port-channel 50:
    description: "MOC-R4PAC## Link"
    state: "up"
    portmode: "trunk"
    tagged: "all"
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/4"
    mlag: "Port-channel 50"
    stp:
      rootguard: true
  Port-channel 60:
    description: "MOC-R4PAC## Link"
    state: "up"
    portmode: "trunk"
    tagged: "all"
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/5"
    mlag: "Port-channel 60"
    stp:
      rootguard: true
  Port-channel 80:
    description: "MOC-R4PAC04 Link"
    state: "up"
    portmode: "trunk"
    tagged: "all"
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/6"
    mlag: "Port-channel 80"
    stp:
      rootguard: true
  Port-channel 90:
    description: "MOC-R4PAC02 Link"
    state: "up"
    portmode: "trunk"
    tagged: "all"
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/7"
    mlag: "Port-channel 90"
    stp:
      rootguard: true
  Port-channel 100:
    description: "MOC-CORE-4 VLT LAG"
    state: "up"
    mtu: 9216
    lag-members:
      - "hundredGigE 1/31"
      - "hundredGigE 1/32"
  Port-channel 101:
    description: "MOC-MCORE-2 Uplink"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged: "all"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/33"
    mlag: "Port-channel 101"
    stp:
      rootguard: true
  Vlan 930:
    state: "up"
    ip4: "10.80.1.4/20"
  Vlan 935:
    state: "up"
    ip4: "10.82.1.4/20"
