---
- name: Define OS9 credentials from AWS securet
  set_fact:
    ansible_ssh_user: "{{ sw_secret['user'] }}"
    ansible_ssh_pass: "{{ sw_secret['pass'] }}"
    ansible_become_pass: "{{ sw_secret['pass'] }}"

# Gather the current output of "show running configuration" on the switch
- name: Gather Current Configuration
  dellemc.os9.os9_facts:
    gather_subset:
      - config
  register: cur_config

- name: Fanout configuration that exists on the switch but not in the manifest
  debug:
    msg: "{{ cur_config | os9_getConfigDiff(interfaces, vlan_interfaces, port_channels, vlans, 'fanout', 'on_switch') }}"

- name: Fanout configuration that exists in the manifest but not on the switch
  debug:
    msg: "{{ cur_config | os9_getConfigDiff(interfaces, vlan_interfaces, port_channels, vlans, 'fanout', 'on_manifest') }}"

- name: Configuration that exists on the switch but not in the manifest
  debug:
    msg: "{{ cur_config | os9_getConfigDiff(interfaces, vlan_interfaces, port_channels, vlans, 'config', 'on_switch') }}"

- name: Configuration that exists in the manifest but not on the switch
  debug:
    msg: "{{ cur_config | os9_getConfigDiff(interfaces, vlan_interfaces, port_channels, vlans, 'config', 'on_manifest') }}"
