interfaces:
  1/1:
    fanout: "quad"
    fanout_speed: "25G"
  1/1/1:
    description: "OCP-CTRL-U36-R"
    state: "up"
    untagged: 209
    tagged:
      - 250
    portmode: "hybrid"
    mtu: 9216
  1/1/2:
    description: "OCP-CTRL-U35-R"
    state: "up"
    untagged: 209
    tagged:
      - 250
    portmode: "hybrid"
    mtu: 9216
  1/1/3:
    description: "OCP-CTRL-U34-R"
    state: "up"
    untagged: 209
    tagged:
      - 250
    portmode: "hybrid"
    mtu: 9216
  1/1/4:
    description: "OCP-CTRL-U33-R"
    state: "down"
  1/2:
    fanout: "quad"
    fanout_speed: "10G"
  1/2/1:
    description: "OCP-CTRL-U32-R"
    state: "down"
  1/2/2:
    description: "OCP-CTRL-U31-R"
    state: "down"
  1/2/3:
    description: "ALANLIU-L"
    state: "up"
    mtu: 9216
    untagged: 10
    portmode: "access"
  1/2/4:
    state: "down"
  1/3:
    state: "down"
  1/4:
    state: "down"
  1/5:
    fanout: "quad"
    fanout_speed: "10G"
  1/5/1:
    description: "OCT-MCORE-1 Port 52 Po20"
    state: "up"
  1/5/2:
    description: "INTEL-U29-R"
    state: "down"
  1/5/3:
    description: "INTEL-U27-R"
    state: "down"
  1/5/4:
    description: "INTEL-U25-R"
    state: "down"
  1/6:
    state: "down"
  1/7:
    state: "down"
  1/8:
    state: "down"
  1/9:
    state: "down"
  1/10:
    state: "down"
  1/11:
    state: "down"
  1/12:
    state: "down"
  1/13:
    description: "OCT5-SW-TORS Port 53 Po50"
    state: "up"
    mtu: 9216
  1/14:
    description: "OCT6-SW-TORS-B Port 54 Po60"
    state: "up"
    mtu: 9216
  1/15:
    state: "down"
  1/16:
    description: "OCT8-SW-TORS Port 54 Po80"
    state: "up"
    mtu: 9216
  1/17:
    state: "down"
  1/18:
    state: "down"
  1/19:
    state: "down"
  1/20:
    state: "down"
  1/21:
    state: "down"
  1/22:
    state: "down"
  1/23:
    state: "down"
  1/24:
    state: "down"
  1/25:
    state: "down"
  1/26:
    state: "down"
  1/27:
    fanout: "single"
    fanout_speed: "40G"
  1/27/1:
    description: "Brocade-15-## Port #### Po11"
    state: "up"
    mtu: 9216
  1/28:
    description: "OCT-CORE-4 Port 2 Po10"
    state: "up"
    mtu: 9216
  1/29:
    description: "OCT-CORE-3 Port 2 Po10"
    state: "up"
    mtu: 9216
  1/30:
    description: "UMA-NESE-CORE Port #### Po30"
    state: "up"
    mtu: 9216
  1/31:
    description: "OCT-CORE-1 Port 31 VLT"
    state: "up"
  1/32:
    description: "OCT-CORE-1 Port 32 VLT"
    state: "up"
  1/33:
    description: "CSAIL Po1000"
    state: "up"
  1/34:
    description: "OCT-CORE-1 Port 34 VLT Heartbeat"
    state: "up"
    ip4: "10.255.255.2/30"
