interfaces:
  hundredGigE 1/1:
    state: "down"
  hundredGigE 1/2:
    state: "down"
  hundredGigE 1/3:
    state: "down"
  hundredGigE 1/4:
    state: "down"
  hundredGigE 1/5:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/5/1:
    description: "OCT-MCORE-1 Port 52 Po20"
    state: "up"
  TenGigabitEthernet 1/5/2:
    description: "INTEL-U29-R"
    state: "down"
  TenGigabitEthernet 1/5/3:
    description: "INTEL-U27-R"
    state: "down"
  TenGigabitEthernet 1/5/4:
    description: "INTEL-U25-R"
    state: "down"
  hundredGigE 1/6:
    state: "down"
  hundredGigE 1/7:
    state: "down"
  hundredGigE 1/8:
    state: "down"
  hundredGigE 1/9:
    state: "down"
  hundredGigE 1/10:
    state: "down"
  hundredGigE 1/11:
    state: "down"
  hundredGigE 1/12:
    state: "down"
  hundredGigE 1/13:
    state: "down"
  hundredGigE 1/14:
    state: "down"
  hundredGigE 1/15:
    state: "down"
  hundredGigE 1/16:
    state: "down"
  hundredGigE 1/17:
    state: "down"
  hundredGigE 1/18:
    state: "down"
  hundredGigE 1/19:
    state: "down"
  hundredGigE 1/20:
    state: "down"
  hundredGigE 1/21:
    state: "down"
  hundredGigE 1/22:
    state: "down"
  hundredGigE 1/23:
    state: "down"
  hundredGigE 1/24:
    state: "down"
  hundredGigE 1/25:
    description: "MOC-CORE-1 Port 26"
    state: "up"
    mtu: 9216
  hundredGigE 1/26:
    state: "down"
  hundredGigE 1/27:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/27/1:
    description: "Brocade-15-## Port #### Po11"
    state: "up"
    mtu: 9216
  hundredGigE 1/28:
    description: "OCT-CORE-4 Port 2 Po10"
    state: "up"
    mtu: 9216
  hundredGigE 1/29:
    description: "OCT-CORE-3 Port 2 Po10"
    state: "up"
    mtu: 9216
  hundredGigE 1/30:
    description: "UMA-NESE-CORE Port #### Po30"
    state: "up"
    mtu: 9216
  hundredGigE 1/31:
    description: "OCT-CORE-1 Port 31 VLT"
    state: "up"
  hundredGigE 1/32:
    description: "OCT-CORE-1 Port 32 VLT"
    state: "up"
  TenGigabitEthernet 1/33:
    description: "CSAIL Po1000"
    state: "up"
  TenGigabitEthernet 1/34:
    description: "OCT-CORE-1 Port 34 VLT Heartbeat"
    state: "up"
    ip4: "10.255.255.2/30"
  Port-channel 10:
    description: "OCT-CORE-3 and OCT-CORE-4 Core LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      # CSAIL
      - 10
      # UMA Public IPs
      - 84
      # MOC Public IPs
      - 105
      - 127
      # MOC
      - 204
      - 207
      - 208
      - 213
      - 250
      # Unity
      - 300
      # ESI
      - 351:499
      - 520:622
      - 623
      - 624:630
      # MGMT
      - 911
      - 913
      - 930
      # AL2S VLANs
      - 3100
      - 3101
      - 3102
      - 3103
      - 3104
      - 3105
      - 3106
      - 3107
      - 3108
      - 3109
      # CSAIL
      - 3801
      - 3802
      - 3803
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/28"
      - "hundredGigE 1/29"
    mlag: "Port-channel 10"
  Port-channel 11:
    description: "MOC Brocade Fabric LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      # CSAIL
      - 10
      # MOC Public IPs
      - 105
      - 127
      # MOC
      - 204
      - 207
      - 208
      - 209
      - 213
      - 250
      # ESI
      - 351:499
      - 520:622
      - 623
      - 624:630
      - 700
      # MGMT
      - 911
      - 912
      - 913
      - 930
      # CSAIL
      - 3801
      - 3802
      - 3803
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "fortyGigE 1/27/1"
    mlag: "Port-channel 11"
  Port-channel 20:
    description: "OCT-MCORE-1 LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      # UMA Public IPs
      - 84
      - 214
      # MOC
      - 127
      - 207
      # Unity
      - 301
      # MGMT
      - 910
      - 911
      - 912
      - 930
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/5/1"
    mlag: "Port-channel 20"
  Port-channel 30:
    description: "UMA-NESE-Core LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      # MOC
      - 211
      # Unity
      - 300
      # UMA NESE
      - 950
      # AL2S VLANs
      - 3100
      - 3101
      - 3102
      - 3103
      - 3104
      - 3105
      - 3106
      - 3107
      - 3108
      - 3109
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/30"
    mlag: "Port-channel 30"
  Port-channel 40:
    description: "MOC-CORE-1 and MOC-CORE-2"
    state: "up"
    portmode: "trunk"
    tagged:
      - 10
      - 127
      - 207
      - 213
      - 214
      - 250
      - 351:499
      - 520:622
      - 623
      - 624:630
      - 911
      - 912
      - 3801
      - 3802
      - 3803
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/25"
    mlag: "Port-channel 40"
  Port-channel 100:
    description: "OCT-CORE-1 VLT LAG"
    state: "up"
    mtu: 9216
    lag-members:
      - "hundredGigE 1/31"
      - "hundredGigE 1/32"
  Port-channel 1000:
    description: "CSAIL LAG"
    state: "up"
    portmode: "hybrid"
    untagged: 10
    tagged:
      # CSAIL
      - 3801
      - 3802
      - 3803
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/33"
    mlag: "Port-channel 1000"
