interfaces:
  Ethernet1/1:
    enabled: true
    description: "NERC-CORE-2 Port 1"
    mtu: 9216
  Ethernet1/2:
    enabled: true
    description: "NERC-CORE-2 Port 2"
    mtu: 9216
  Ethernet1/3:
    enabled: true
    description: "NERC-CORE-2 Port 3"
    mtu: 9216
  Ethernet1/4:
    enabled: true
    description: "NERC-CORE-2 Port 4"
    mtu: 9216
  Ethernet1/5:
    description: "CES1-S3-P1"
    enabled: true
    mtu: 9216
  Ethernet1/6:
    description: "CES2-S3-P1"
    enabled: true
    mtu: 9216
  Ethernet1/7:
    description: "AFM1-S3-P1"
    enabled: true
    mtu: 9216
  Ethernet1/8:
    description: "AFM2-S3-P1"
    enabled: true
    mtu: 9216
  Ethernet1/9:
    enabled: false
  Ethernet1/10:
    enabled: false
  Ethernet1/11:
    enabled: false
  Ethernet1/12:
    enabled: false
  Ethernet1/13:
    enabled: false
  Ethernet1/14:
    enabled: false
  Ethernet1/15:
    enabled: false
  Ethernet1/16:
    enabled: false
  Ethernet1/17:
    enabled: false
  Ethernet1/18:
    enabled: false
  Ethernet1/19:
    enabled: false
  Ethernet1/20:
    enabled: false
  Ethernet1/21:
    enabled: false
  Ethernet1/22:
    enabled: false
  Ethernet1/23:
    enabled: true
    description: "GPU-CORE-1 Port 31"
    mtu: 9216
    portmode: trunk
  Ethernet1/24:
    enabled: true
    description: "GPU-CORE-2 Port 31"
    mtu: 9216
    portmode: trunk
  Ethernet1/25:
    enabled: true
    description: "NERC-SW-R8-PA-C23-TORS Port 49"
  Ethernet1/26:
    enabled: true
    description: "NERC-SW-R2-PC-C21-TORS Port 53"
  Ethernet1/27:
    enabled: true
    description: "NERC-SW-R2-PC-C06-TORS Port 53"
  Ethernet1/28:
    enabled: true
    description: "NERC-SW-R1-PC-C20-TORS-A Port X"
  Ethernet1/29:
    enabled: true
    description: "MOC-SW-R4PCC02-SW-BORS Port 31"
  Ethernet1/30:
    enabled: true
    description: "MOC-SW-R4PCC04-SW-BORS Port 31"
  Ethernet1/31:
    enabled: false
  Ethernet1/32:
    enabled: false
  Ethernet1/33:
    enabled: true
    description: "Harvard R6-PA-C15 Shared Aggregation Port 25"
  Ethernet1/34:
    enabled: true
    description: "Harvard R6-PA-C13 Shared Aggregation Port 26"
  Ethernet1/35:
    enabled: true
    description: "MOC-CORE-1 Port 21"
    fec: false
  Ethernet1/36:
    enabled: true
    description: "MOC-CORE-2 Port 21"
    fec: false
  port-channel1:
    enabled: true
    description: "VPC peer-link"
    portmode: trunk
    mode: "lacp"
    managed: true
    lacp-rate: "fast"
    lacp-members-active:
      - "Ethernet1/1"
      - "Ethernet1/2"
      - "Ethernet1/3"
      - "Ethernet1/4"
  port-channel10:
    enabled: true
    description: "Harvard Shared Aggregation"
    mtu: 9216
    portmode: trunk
    tagged:
      - 2141:2148
      - 2170
      - 2172:2180
      - 2180
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "Ethernet1/33"
      - "Ethernet1/34"
    mlag: "10"
  port-channel20:
    enabled: true
    description: "MOC core"
    mtu: 9216
    autoneg: false
    speed: 100000
    stp:
      disabled: true
    portmode: trunk
    tagged:
      - 204
      - 211
      - 300
      - 350
      - 351:630
      - 911
      - 930
      - 935
      - 2076
      - 2141:2148
      - 2170
      - 2172:2180
      - 2180
      - 2303
      - 2304
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "Ethernet1/35"
      - "Ethernet1/36"
    mlag: "20"
  port-channel50:
    enabled: true
    description: "R2-PC-C21 TORS"
    mtu: 9216
    portmode: trunk
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "Ethernet1/26"
    mlag: "50"
  port-channel51:
    enabled: true
    description: "R2-PC-C06 TORS"
    mtu: 9216
    portmode: trunk
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "Ethernet1/27"
    mlag: "51"
  port-channel52:
    enabled: true
    description: "R8-PA-C23 TORS"
    mtu: 9216
    portmode: trunk
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "Ethernet1/25"
    mlag: "52"
  port-channel53:
    enabled: true
    description: "GPU-CORE"
    mtu: 9216
    portmode: trunk
    stp:
      disabled: true
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "Ethernet1/23"
      - "Ethernet1/24"
    mlag: "53"
  port-channel55:
    enabled: true
    description: "R1-PC-C20 TORS"
    mtu: 9216
    portmode: trunk
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "Ethernet1/28"
    mlag: "55"
  port-channel56:
    enabled: true
    description: "R4-PC-C02 BORS"
    mtu: 9216
    portmode: trunk
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "Ethernet1/29"
    mlag: "56"
  port-channel57:
    enabled: true
    description: "R4-PC-C04 BORS"
    mtu: 9216
    portmode: trunk
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "Ethernet1/30"
    mlag: "57"
  port-channel101:
    enabled: true
    description: "IBM Scale CES1"
    mtu: 9216
    mode: "lacp"
    portmode: access
    untagged: 211
    lacp-rate: "fast"
    lacp-members-active:
      - "Ethernet1/5"
    mlag: "101"
  port-channel102:
    enabled: true
    description: "IBM Scale CES2"
    mtu: 9216
    mode: "lacp"
    portmode: access
    untagged: 211
    lacp-rate: "fast"
    lacp-members-active:
      - "Ethernet1/6"
    mlag: "102"
  port-channel103:
    enabled: true
    description: "IBM Scale AFM1"
    mtu: 9216
    portmode: access
    untagged: 211
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "Ethernet1/7"
    mlag: "103"
  port-channel104:
    enabled: true
    description: "IBM Scale AFM2"
    mtu: 9216
    portmode: access
    untagged: 211
    mode: "lacp"
    lacp-rate: "fast"
    lacp-members-active:
      - "Ethernet1/8"
    mlag: "104"
