# Gather the current output of "show running configuration" on the switch
- name: Gather current configuration
  dellemc.os9.os9_facts:
    gather_subset:
      - config
  register: cur_config

# This task creates a dictionary of VLANs created from
# the global configuration
- name: Generate VLAN dictionary
  set_fact:
    vlan_dict: "{{ vlans | get_vlan_dict(group_names) }}"

# Set the hostname of the switch to the value in the hosts file
- name: Set hostname
  dellemc.os9.os9_config:
    lines:
      - hostname {{ inventory_hostname }}

# Disable the telnet server on the switch
- name: Disable telnet server
  dellemc.os9.os9_config:
    lines:
      - no ip telnet server enable

# This task reads the host vars and updates configuration
- name: Apply Host Configuration
  dellemc.os9.os9_config:
    lines: "{{ item.1 }}"
    parents: "{{ item.0 }}"
  loop: "{{ cur_config | os9_getConfiguration(interfaces, vlan_interfaces, port_channels, vlan_dict) }}"
