---
- name: Generate host-specific VLAN manifest
  set_fact:
    vlans_host: "{{ vlans | FILTER_VLANS(group_names) }}"

- name: Import Dell OS9 Tasks
  ansible.builtin.include_tasks: dell_os9.yaml
  when: ansible_network_os == "dellemc.os9.os9"

- name: Import Cisco NXOS Tasks
  ansible.builtin.include_tasks: cisco_nxos.yaml
  when: ansible_network_os == "cisco.nxos.nxos"
