interfaces:
  TenGigabitEthernet 1/1:
    description: "OCT1-U1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/2:
    description: "OCT1-U2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/3:
    description: "OCT1-U3"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/4:
    description: "OCT1-U4"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/5:
    description: "OCT1-U5"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/6:
    description: "OCT1-U6"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/7:
    description: "OCT1-U7"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/8:
    description: "OCT1-U8"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/9:
    description: "OCT1-U9"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/10:
    description: "OCT1-U10"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/11:
    description: "OCT1-U11"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/12:
    description: "OCT1-U12"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/13:
    description: "OCT1-U13"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/14:
    description: "OCT1-U14"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/15:
    description: "OCT1-U15"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/16:
    description: "OCT1-U16"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/17:
    description: "OCT1-U17"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/18:
    description: "OCT1-U18"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/19:
    description: "OCT1-U19"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/20:
    description: "OCT1-U20"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/21:
    description: "OCT1-U21"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/22:
    description: "OCT1-U22"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/23:
    description: "OCT1-U23"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/24:
    description: "OCT1-U24"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/25:
    description: "OCT1-U25"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/26:
    description: "OCT1-U26"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/27:
    description: "OCT1-U27"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/28:
    description: "OCT1-U28"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/29:
    description: "OCT1-U29"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/30:
    description: "OCT1-U30"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/31:
    description: "OCT1-U31"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/32:
    description: "OCT1-U32"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/33:
    description: "OCT1-U33"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/34:
    description: "OCT1-U34"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/35:
    description: "OCT1-U35"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/36:
    description: "OCT1-U36"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/37:
    description: "OCT1-U37"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/38:
    description: "OCT1-U38"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/39:
    state: "down"
  TenGigabitEthernet 1/40:
    state: "down"
  TenGigabitEthernet 1/41:
    state: "down"
  TenGigabitEthernet 1/42:
    state: "down"
  TenGigabitEthernet 1/43:
    state: "down"
  TenGigabitEthernet 1/44:
    state: "down"
  TenGigabitEthernet 1/45:
    description: "OCT1-SW-MGMT Port 51"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/46:
    description: "OCT1-SW-MGMT Port 52"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/47:
    state: "down"
  TenGigabitEthernet 1/48:
    description: "OCT1-SW-CTRL"
    state: "up"
    portmode: "access"
    untagged: 84
  fortyGigE 1/49:
    state: "down"
  fortyGigE 1/50:
    state: "down"
  fortyGigE 1/51:
    state: "down"
  fortyGigE 1/52:
    state: "down"
  fortyGigE 1/53:
    description: "OCT-CORE-3 Port #### Po1"
    state: "up"
    mtu: 9216
  fortyGigE 1/54:
    description: "OCT-CORE-3 Port #### Po1"
    state: "up"
    mtu: 9216
  Port-channel 1:
    description: "OCT-CORE-3 LAG"
    state: "up"
    portmode: "trunk"
    tagged: "all"
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "fortyGigE 1/53"
      - "fortyGigE 1/54"
  Port-channel 101:
    description: "OCT1-SW-MGMT Uplink"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged: "all"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/45"
      - "TenGigabitEthernet 1/46"
  Vlan 910:
    state: "up"
    ip4: "10.0.0.4/22"
  Vlan 931:
    state: "up"
    ip4: "10.81.2.11/20"
