interfaces:
  1/1:
    description: "OCT-CORE-1 Port 28 Po10"
    state: "up"
    mtu: 9216
  1/2:
    description: "OCT-CORE-2 Port 28 Po10"
    state: "up"
    mtu: 9216
  1/3:
    state: "down"
  1/4:
    state: "down"
  1/5:
    state: "down"
  1/6:
    state: "down"
  1/7:
    state: "down"
  1/8:
    state: "down"
  1/9:
    state: "down"
  1/10:
    state: "down"
  1/11:
    state: "down"
  1/12:
    state: "down"
  1/13:
    state: "down"
  1/14:
    state: "down"
  1/15:
    state: "down"
  1/16:
    state: "down"
  1/17:
    state: "down"
  1/18:
    state: "down"
  1/19:
    state: "down"
  1/20:
    state: "down"
  1/21:
    state: "down"
  1/22:
    state: "down"
  1/23:
    state: "down"
  1/24:
    state: "down"
  1/25:
    state: "down"
  1/26:
    state: "down"
  1/27:
    description: "OCT-CORE-3 Port 27 VLT"
    state: "up"
  1/28:
    description: "OCT-CORE-3 Port 28 VLT"
    state: "up"
  1/29:
    state: "down"
  1/30:
    state: "down"
  1/31:
    fanout: "single"
    fanout_speed: "40G"
  1/31/1:
    description: "UNITY-CORE-1 Port #### Po200"
    state: "up"
    mtu: 9216
  1/32:
    state: "down"
  1/33:
    description: "OCT-MCORE-2 Port 52 Po300"
    state: "up"
    mtu: 9216
  1/34:
    description: "OCT-CORE-4 Port 34 VLT Heartbeat"
    state: "up"
    ip4: "10.255.255.2/30"
