port_channels:
  10:
    description: "OCT-CORE-1 and OCT-CORE-2 Core LAG"
    state: "up"
    tagged: "all"
    mtu: 9216
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/1"
      - "1/2"
    custom:
      - "vlt-peer-lag port-channel 10"
  100:
    description: "OCT-CORE-3 VLT LAG"
    state: "up"
    mode: "normal"
    interfaces:
      - "1/27"
      - "1/28"
  300:
    description: "OCT-MCORE-2 LAG"
    state: "up"
    mode: "lacp"
    tagged:
      - 910
      - 911
      - 912
      - 930
