port_channels:
  10:
    description: "OCT-CORE-1 and OCT-CORE-2 Core LAG"
    state: "up"
    tagged:
      # CSAIL
      - 10
      # UMA Public IPs
      - 57
      - 84
      - 86
      # MOC Public IPs
      - 105
      - 127
      # MOC
      - 207
      - 208
      - 213
      - 250
      # Unity
      - 300
      # ESI
      - 351:499
      - 520:622
      - 623
      - 624:630
      # MGMT
      - 911
      - 913
      # UMA NESE
      - 950
      # AL2S VLANs
      - 3100
      - 3101
      - 3102
      - 3103
      - 3104
      - 3105
      - 3106
      - 3107
      - 3108
      - 3109
      # CSAIL
      - 3801
      - 3803
    portmode: "trunk"
    mtu: 9216
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/1"
      - "1/2"
    custom:
      - "vlt-peer-lag port-channel 10"
  100:
    description: "OCT-CORE-3 VLT LAG"
    state: "up"
    mode: "normal"
    mtu: 9216
    interfaces:
      - "1/27"
      - "1/28"
  200:
    description: "UNITY-CORE-1 LAG"
    state: "up"
    tagged:
      # UNITY
      - 300
      - 301
    portmode: "trunk"
    mtu: 9216
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/31/1"
    custom:
      - "vlt-peer-lag port-channel 200"
  300:
    description: "OCT-MCORE-2 LAG"
    state: "up"
    mode: "lacp"
    lacp-rate: "fast"
    interfaces:
      - "1/33"
    tagged:
      # MGMT
      - 910
      - 911
      - 912
      - 913
      - 930
    portmode: "trunk"
    custom:
      - "vlt-peer-lag port-channel 300"
