name: Unit tests

on: [push, pull_request]

jobs:
  run-unit-tests:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
      - name: Unit Tests
        run: pytest --cov=filter_plugins -rXxs
